/**
 * Supabase Database types — generated by scripts/gen-supabase-types.sh
 * Do not edit by hand; re-run after schema migrations.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      appointments: {
        Row: {
          calendar_event_id: string | null
          confirmation_code: string
          created_at: string
          duration_minutes: number | null
          external_event_id: string | null
          id: string
          patient_name: string
          patient_phone: string | null
          provider_name: string | null
          scheduled_timestamp: string | null
          session_id: string | null
          slot_end: string
          slot_start: string
          status: string
          tenant_id: string
          treatment_type: string | null
        }
        Insert: {
          calendar_event_id?: string | null
          confirmation_code: string
          created_at?: string
          duration_minutes?: number | null
          external_event_id?: string | null
          id?: string
          patient_name: string
          patient_phone?: string | null
          provider_name?: string | null
          scheduled_timestamp?: string | null
          session_id?: string | null
          slot_end: string
          slot_start: string
          status?: string
          tenant_id: string
          treatment_type?: string | null
        }
        Update: {
          calendar_event_id?: string | null
          confirmation_code?: string
          created_at?: string
          duration_minutes?: number | null
          external_event_id?: string | null
          id?: string
          patient_name?: string
          patient_phone?: string | null
          provider_name?: string | null
          scheduled_timestamp?: string | null
          session_id?: string | null
          slot_end?: string
          slot_start?: string
          status?: string
          tenant_id?: string
          treatment_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "appointments_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "patient_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          id: string
          metadata: Json
          resource_id: string
          resource_type: string
          tenant_id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          resource_id: string
          resource_type: string
          tenant_id: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          resource_id?: string
          resource_type?: string
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      clinic_documents: {
        Row: {
          category: string
          chunk_count: number
          created_at: string
          file_hash: string
          id: string
          ingested_by: string
          source_filename: string
          tenant_id: string
        }
        Insert: {
          category: string
          chunk_count?: number
          created_at?: string
          file_hash: string
          id?: string
          ingested_by: string
          source_filename: string
          tenant_id: string
        }
        Update: {
          category?: string
          chunk_count?: number
          created_at?: string
          file_hash?: string
          id?: string
          ingested_by?: string
          source_filename?: string
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "clinic_documents_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      clinic_protocols: {
        Row: {
          category: string
          chunk_index: number
          content_payload: string
          created_at: string
          document_id: string
          embedding: string
          file_hash: string
          id: string
          ingested_by: string
          source_filename: string
          tenant_id: string
          token_count: number
        }
        Insert: {
          category: string
          chunk_index: number
          content_payload: string
          created_at?: string
          document_id: string
          embedding: string
          file_hash: string
          id?: string
          ingested_by: string
          source_filename: string
          tenant_id: string
          token_count?: number
        }
        Update: {
          category?: string
          chunk_index?: number
          content_payload?: string
          created_at?: string
          document_id?: string
          embedding?: string
          file_hash?: string
          id?: string
          ingested_by?: string
          source_filename?: string
          tenant_id?: string
          token_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "clinic_protocols_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "clinic_documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "clinic_protocols_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      emergency_keyword_config: {
        Row: {
          created_at: string
          description: string | null
          id: string
          is_active: boolean
          pattern: string
          reviewed_at: string | null
          reviewed_by: string | null
          tenant_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          pattern: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          tenant_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          pattern?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          tenant_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "emergency_keyword_config_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      ingestion_jobs: {
        Row: {
          category: string
          chunks_done: number
          chunks_total: number
          created_at: string
          document_id: string | null
          error_message: string | null
          file_hash: string
          filename: string
          id: string
          ingested_by: string
          progress_pct: number
          status: string
          tenant_id: string
          updated_at: string
        }
        Insert: {
          category: string
          chunks_done?: number
          chunks_total?: number
          created_at?: string
          document_id?: string | null
          error_message?: string | null
          file_hash: string
          filename: string
          id?: string
          ingested_by: string
          progress_pct?: number
          status?: string
          tenant_id: string
          updated_at?: string
        }
        Update: {
          category?: string
          chunks_done?: number
          chunks_total?: number
          created_at?: string
          document_id?: string | null
          error_message?: string | null
          file_hash?: string
          filename?: string
          id?: string
          ingested_by?: string
          progress_pct?: number
          status?: string
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ingestion_jobs_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "clinic_documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ingestion_jobs_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      langgraph_checkpoints: {
        Row: {
          checkpoint_data: Json
          session_id: string
          tenant_id: string
          thread_id: string
          updated_at: string
        }
        Insert: {
          checkpoint_data?: Json
          session_id: string
          tenant_id: string
          thread_id: string
          updated_at?: string
        }
        Update: {
          checkpoint_data?: Json
          session_id?: string
          tenant_id?: string
          thread_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "langgraph_checkpoints_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "patient_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "langgraph_checkpoints_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      patient_sessions: {
        Row: {
          ai_summary: string | null
          created_at: string
          current_triage_status: string | null
          escalated_at: string | null
          id: string
          langgraph_thread_id: string | null
          message_history: Json
          metadata: Json
          patient_name: string | null
          status: string
          tenant_id: string
          updated_at: string
        }
        Insert: {
          ai_summary?: string | null
          created_at?: string
          current_triage_status?: string | null
          escalated_at?: string | null
          id?: string
          langgraph_thread_id?: string | null
          message_history?: Json
          metadata?: Json
          patient_name?: string | null
          status?: string
          tenant_id: string
          updated_at?: string
        }
        Update: {
          ai_summary?: string | null
          created_at?: string
          current_triage_status?: string | null
          escalated_at?: string | null
          id?: string
          langgraph_thread_id?: string | null
          message_history?: Json
          metadata?: Json
          patient_name?: string | null
          status?: string
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "patient_sessions_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          full_name: string | null
          id: string
          role: string
          tenant_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          full_name?: string | null
          id: string
          role?: string
          tenant_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          full_name?: string | null
          id?: string
          role?: string
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenants: {
        Row: {
          created_at: string
          hipaa_baa_signed_at: string | null
          hipaa_baa_signed_by: string | null
          id: string
          name: string
          slug: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          hipaa_baa_signed_at?: string | null
          hipaa_baa_signed_by?: string | null
          id?: string
          name: string
          slug: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          hipaa_baa_signed_at?: string | null
          hipaa_baa_signed_by?: string | null
          id?: string
          name?: string
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      complete_onboarding: {
        Args: { p_clinic_name: string; p_clinic_slug: string; p_role?: string }
        Returns: string
      }
      custom_access_token_hook: { Args: { event: Json }; Returns: Json }
      match_clinic_protocols: {
        Args: {
          match_count?: number
          match_tenant_id: string
          match_threshold?: number
          query_embedding: string
        }
        Returns: {
          category: string
          chunk_index: number
          content_payload: string
          document_id: string
          id: string
          similarity: number
          source_filename: string
        }[]
      }
      purge_expired_patient_sessions: { Args: never; Returns: number }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const
