/**
 * Supabase Database types — generated by scripts/gen-supabase-types.sh
 * Do not edit by hand; re-run `npm run gen:types` after schema migrations.
 * Regenerate when schema changes: npm run gen:types (requires Supabase CLI + linked project).
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type SessionStatus = "active" | "completed" | "abandoned";
export type AppointmentStatus = "pending" | "confirmed" | "cancelled" | "no_show" | "completed";
export type IngestionJobStatus = "pending" | "processing" | "completed" | "failed" | "partial";
export type DocumentCategory =
  | "treatment_protocol"
  | "pricing"
  | "insurance"
  | "faq"
  | "other";

export interface ChatMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string;
          slug: string;
          name: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          tenant_id: string;
          full_name: string | null;
          role: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          tenant_id: string;
          full_name?: string | null;
          role?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          full_name?: string | null;
          role?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      patient_sessions: {
        Row: {
          id: string;
          tenant_id: string;
          status: SessionStatus;
          metadata: Json;
          created_at: string;
          updated_at: string;
          langgraph_thread_id: string | null;
          current_triage_status: string | null;
          ai_summary: string | null;
          message_history: ChatMessage[];
          escalated_at: string | null;
          patient_name: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          status?: SessionStatus;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          langgraph_thread_id?: string | null;
          current_triage_status?: string | null;
          ai_summary?: string | null;
          message_history?: ChatMessage[];
          escalated_at?: string | null;
          patient_name?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          status?: SessionStatus;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          langgraph_thread_id?: string | null;
          current_triage_status?: string | null;
          ai_summary?: string | null;
          message_history?: ChatMessage[];
          escalated_at?: string | null;
          patient_name?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "patient_sessions_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      appointments: {
        Row: {
          id: string;
          tenant_id: string;
          session_id: string | null;
          patient_name: string;
          patient_phone: string | null;
          slot_start: string;
          slot_end: string;
          confirmation_code: string;
          calendar_event_id: string | null;
          status: AppointmentStatus;
          created_at: string;
          provider_name: string | null;
          treatment_type: string | null;
          scheduled_timestamp: string | null;
          duration_minutes: number | null;
          external_event_id: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          session_id?: string | null;
          patient_name: string;
          patient_phone?: string | null;
          slot_start: string;
          slot_end: string;
          confirmation_code: string;
          calendar_event_id?: string | null;
          status?: AppointmentStatus;
          created_at?: string;
          provider_name?: string | null;
          treatment_type?: string | null;
          scheduled_timestamp?: string | null;
          duration_minutes?: number | null;
          external_event_id?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          session_id?: string | null;
          patient_name?: string;
          patient_phone?: string | null;
          slot_start?: string;
          slot_end?: string;
          confirmation_code?: string;
          calendar_event_id?: string | null;
          status?: AppointmentStatus;
          created_at?: string;
          provider_name?: string | null;
          treatment_type?: string | null;
          scheduled_timestamp?: string | null;
          duration_minutes?: number | null;
          external_event_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "appointments_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "appointments_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "patient_sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      clinic_documents: {
        Row: {
          id: string;
          tenant_id: string;
          source_filename: string;
          category: DocumentCategory;
          file_hash: string;
          chunk_count: number;
          ingested_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          source_filename: string;
          category: DocumentCategory;
          file_hash: string;
          chunk_count?: number;
          ingested_by: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          source_filename?: string;
          category?: DocumentCategory;
          file_hash?: string;
          chunk_count?: number;
          ingested_by?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "clinic_documents_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      ingestion_jobs: {
        Row: {
          id: string;
          tenant_id: string;
          document_id: string | null;
          filename: string;
          category: string;
          file_hash: string;
          status: IngestionJobStatus;
          progress_pct: number;
          chunks_total: number;
          chunks_done: number;
          error_message: string | null;
          ingested_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          document_id?: string | null;
          filename: string;
          category: string;
          file_hash: string;
          status?: IngestionJobStatus;
          progress_pct?: number;
          chunks_total?: number;
          chunks_done?: number;
          error_message?: string | null;
          ingested_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          document_id?: string | null;
          filename?: string;
          category?: string;
          file_hash?: string;
          status?: IngestionJobStatus;
          progress_pct?: number;
          chunks_total?: number;
          chunks_done?: number;
          error_message?: string | null;
          ingested_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ingestion_jobs_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      match_clinic_protocols: {
        Args: {
          query_embedding: number[];
          match_tenant_id: string;
          match_threshold?: number;
          match_count?: number;
        };
        Returns: {
          id: string;
          document_id: string;
          content_payload: string;
          category: string;
          similarity: number;
        }[];
      };
      complete_onboarding: {
        Args: {
          p_clinic_name: string;
          p_clinic_slug: string;
          p_role?: string;
        };
        Returns: string;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

/** Convenience aliases — use these in app code. */
export type PatientSessionRow = Database["public"]["Tables"]["patient_sessions"]["Row"];
export type AppointmentRow = Database["public"]["Tables"]["appointments"]["Row"];
export type ClinicDocumentRow = Database["public"]["Tables"]["clinic_documents"]["Row"];
export type IngestionJobRow = Database["public"]["Tables"]["ingestion_jobs"]["Row"];
export type ProfileRow = Database["public"]["Tables"]["profiles"]["Row"];
