#!/usr/bin/env bash
# Regenerate frontend/src/types/database.ts from a linked Supabase project.
#
# Setup once:
#   npm install --prefix backend
#   cd backend && npx supabase login
#   npm run db:link -- --project-ref <your-project-ref>
#   npm run gen:types
#
# CI / non-interactive:
#   SUPABASE_ACCESS_TOKEN=<token> SUPABASE_PROJECT_REF=<ref> npm run gen:types

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=scripts/db/_lib.sh
source "$ROOT/scripts/db/_lib.sh"

OUT="$ROOT/frontend/src/types/database.ts"
HEADER='/**
 * Supabase Database types — generated by scripts/gen-supabase-types.sh
 * Do not edit by hand; re-run after schema migrations.
 */

'

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

run_gen_types() {
  asp_run_supabase gen types typescript "$@"
}

# shellcheck disable=SC2086
if run_gen_types --linked >"$TMP" 2>/dev/null; then
  printf '%s' "$HEADER" >"$OUT"
  cat "$TMP" >>"$OUT"
  echo "Wrote $OUT (from linked project)"
elif [[ -n "${SUPABASE_PROJECT_REF:-}" ]]; then
  if [[ -n "${SUPABASE_ACCESS_TOKEN:-}" ]]; then
    link_args=(link --project-ref "$SUPABASE_PROJECT_REF")
    if [[ -n "${SUPABASE_DB_PASSWORD:-}" ]]; then
      link_args+=(--password "$SUPABASE_DB_PASSWORD")
    fi
    asp_run_supabase "${link_args[@]}" >/dev/null
  fi
  # shellcheck disable=SC2086
  run_gen_types --project-id "$SUPABASE_PROJECT_REF" >"$TMP"
  printf '%s' "$HEADER" >"$OUT"
  cat "$TMP" >>"$OUT"
  echo "Wrote $OUT (project $SUPABASE_PROJECT_REF)"
else
  echo "WARN: No linked project and SUPABASE_PROJECT_REF unset." >&2
  echo "      Keeping existing types at $OUT" >&2
  echo "      Run: npm run db:link -- --project-ref <ref>  then npm run gen:types" >&2
  exit 0
fi
